Verify checksum of downloaded utilities during CI (#1322)
* remove installs without verifying checksum

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

* set path for extracted binary

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

* add additional messages during install

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

* install kind version from matrix set instead of hardcoding

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

diff --git a/.github/workflows/donotsubmit.yaml b/.github/workflows/donotsubmit.yaml
--- a/.github/workflows/donotsubmit.yaml
+++ b/.github/workflows/donotsubmit.yaml
@@ -27,8 +27,17 @@ jobs:
           TEMP_PATH="$(mktemp -d)"
           PATH="${TEMP_PATH}:$PATH"
 
-          echo '::group::🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog'
-          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b "${TEMP_PATH}" 2>&1
+          echo '::group::🐶 Installing reviewdog v0.13.1 ... https://github.com/reviewdog/reviewdog'
+          reviewdog_sha='08a5a323939101195af1d420ab6be3a50ec12f58e3419e3fcd07b6871f0b9a7e'
+          curl -s -L https://github.com/reviewdog/reviewdog/releases/download/v0.13.1/reviewdog_0.13.1_Linux_x86_64.tar.gz --output "${TEMP_PATH}/reviewdog.tar.gz"
+          echo '::group::🐶 Verifying checksum of download'
+          computed_sha=`sha256sum ${TEMP_PATH}/reviewdog.tar.gz|cut -d ' ' -f 1`
+          if [[ $reviewdog_sha != $computed_sha ]]; then
+            echo '::group::🐶 Failed to verify checksum, exiting!'
+            exit 1
+          fi
+          echo '::group::🐶 Checksum verified successfully, extracting reviewdog'
+          tar zxf "${TEMP_PATH}/reviewdog.tar.gz" -C ${TEMP_PATH} reviewdog
           echo '::endgroup::'
 
           echo '::group:: Running DO NOT SUBMIT with reviewdog 🐶 ...'
