Fix publicKey unmarshal - Add key sign verify for cosigned github workflow
Signed-off-by: Denny Hoang <dhoang@vmware.com>

diff --git a/.github/workflows/kind-cluster-image-policy.yaml b/.github/workflows/kind-cluster-image-policy.yaml
--- a/.github/workflows/kind-cluster-image-policy.yaml
+++ b/.github/workflows/kind-cluster-image-policy.yaml
@@ -120,9 +120,9 @@ jobs:
         echo Created image $demoimage2
         popd
 
-    - name: Deploy ClusterImagePolicy
+    - name: Deploy ClusterImagePolicy With Keyless Signing
       run: |
-        kubectl apply -f ./test/testdata/cosigned/e2e/cip.yaml
+        kubectl apply -f ./test/testdata/cosigned/e2e/cip-keyless.yaml
 
     - name: Sign demoimage with cosign
       run: |
@@ -134,12 +134,12 @@ jobs:
 
     - name: Deploy jobs and verify signed works, unsigned fails
       run: |
-        kubectl create namespace demo
-        kubectl label namespace demo cosigned.sigstore.dev/include=true
+        kubectl create namespace demo-keyless-signing
+        kubectl label namespace demo-keyless-signing cosigned.sigstore.dev/include=true
 
         echo '::group:: test job success'
         # We signed this above, this should work
-        if ! kubectl create -n demo job demo --image=${{ env.demoimage }} ; then
+        if ! kubectl create -n demo-keyless-signing job demo --image=${{ env.demoimage }} ; then
           echo Failed to create Job in namespace without label!
           exit 1
         else
@@ -149,7 +149,56 @@ jobs:
 
         echo '::group:: test job rejection'
         # We did not sign this, should fail
-        if kubectl create -n demo job demo2 --image=${{ env.demoimage2 }} ; then
+        if kubectl create -n demo-keyless-signing job demo2 --image=${{ env.demoimage2 }} ; then
+          echo Failed to block unsigned Job creation!
+          exit 1
+        else
+          echo Successfully blocked Job creation with unsigned image
+        fi
+        echo '::endgroup::'
+
+    - name: Generate New Signing Key
+      run: |
+        COSIGN_PASSWORD="" ./cosign generate-key-pair
+
+    - name: Deploy ClusterImagePolicy With Key Signing
+      run: |
+        yq '. | .spec.authorities[0].key.data |= load_str("cosign.pub")' ./test/testdata/cosigned/e2e/cip-key.yaml | \
+          kubectl apply -f -
+
+    - name: Verify with two CIP, one not signed with public key
+      run: |
+        if kubectl create -n demo-key-signing job demo --image=${{ env.demoimage }}; then
+          echo Failed to block unsigned Job creation!
+          exit 1
+        fi
+
+    - name: Sign demoimage with cosign key
+      run: |
+        ./cosign sign --key cosign.key --force --allow-insecure-registry ${{ env.demoimage }}
+
+    - name: Verify with cosign
+      run: |
+        ./cosign verify --key cosign.pub --allow-insecure-registry ${{ env.demoimage }}
+
+    - name: Deploy jobs and verify signed works, unsigned fails
+      run: |
+        kubectl create namespace demo-key-signing
+        kubectl label namespace demo-key-signing cosigned.sigstore.dev/include=true
+
+        echo '::group:: test job success'
+        # We signed this above, this should work
+        if ! kubectl create -n demo-key-signing job demo --image=${{ env.demoimage }} ; then
+          echo Failed to create Job in namespace without label!
+          exit 1
+        else
+          echo Succcessfully created Job with signed image
+        fi
+        echo '::endgroup:: test job success'
+
+        echo '::group:: test job rejection'
+        # We did not sign this, should fail
+        if kubectl create -n demo-key-signing job demo2 --image=${{ env.demoimage2 }} ; then
           echo Failed to block unsigned Job creation!
           exit 1
         else
